### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Zeirous** [hiimjustin000/IntegratedDemonlist#1]
Why don't you put the demon list icon in the default search tab? It would be way more convenient to have it there instead of the lists its super hidden and I didn't know until I read the description. Also I'm curious why [pointercrate ](https://pointercrate.com/demonlist/)isn't used when its the most popular
![image](https://github.com/hiimjustin000/IntegratedDemonlist/assets/84685318/201f4468-b826-4caa-91f0-2c573ae7127a)

**Comment by hiimjasmine00** [comment]
- This will be implemented in version 1.3.2.
- Pointercrate is not used because their API is complete dogwater. AREDL has basically the same rankings and then some.
