### ISSUE TITLE
GD WONT OPEN!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by BurhanYasir123** [hiimjustin000/IntegratedDemonlist#12]
2024-10-26T22:03:07+0500
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.8.1
Loader Commit: 47e0ca5
Bindings Commit: 7fbb83d
Installed mods: 44
Problems: 0

== Exception Information ==
C++ Exception: class std::bad_variant_access("bad variant access")
Faulty Mod: Integrated Demonlist v1.6.3 (hiimjustin000.integrated_demonlist)
Crashed thread: Main

== Stack Trace ==
 - C:\WINDOWS\System32\KERNELBASE.dll + 3b699 (RaiseException + 105)
 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll + 5267 (CxxThrowException + 151)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geode.dll + 56f99 (std::_Throw_bad_variant_access + 41 | /home/runner/work/geode/geode/.xwin-cache/splat/crt/include/exception:411)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geode.dll + 29fe39 (matjson::Value::as_array + 73 | /home/runner/work/geode/geode/cpm-cache/json/7be1271964142fe09a9ce8136cda20080acc1e08/src/value.hpp:66)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + d2fe
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 121a4
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 12340
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 58b4
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\geode\unzipped\hiimjustin000.integrated_demonlist\hiimjustin000.integrated_demonlist.dll + 523c
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geode.dll + 7b3bb (geode::DefaultEventListenerPool::handle + 491 | /home/runner/work/geode/geode/loader/src/loader/Event.cpp:52)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geode.dll + 154223 (geode::Task<geode::utils::web::WebResponse,geode::utils::web::WebProgress>::finish::<lambda_1>::operator() + 227 | /home/runner/work/geode/geode/loader/include/Geode/loader/../utils/Task.hpp:275)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geode.dll + 8de12 (geode::Loader::Impl::executeMainThreadQueue + 242 | /home/runner/work/geode/geode/loader/src/loader/LoaderImpl.cpp:879)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geode.dll + 6810d (geode::modifier::AsStaticFunction_update<FunctionQueue,void (FunctionQueue::*)(float)>::Impl<void (FunctionQueue::*)(float)>::function + 29 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCScheduler.hpp:115)
 - 00000207C3864482 (Hook handler)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - 00000207C59C8082 (Hook handler)
 - 00000207C59C8082 (Hook handler)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\libcocos2d.dll + bc33b
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\GeometryDash.exe + 4a2d69
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geode.dll + 2910da (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - E:\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\Geometry.Dash.v2.206a\GeometryDash.exe + 4a415a
 - C:\WINDOWS\System32\KERNEL32.DLL + 17374 (BaseThreadInitThunk + 20)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 4cc91 (RtlUserThreadStart + 33)

== Register States ==
RAX: 00007ff994b2fa7f
RBX: 0000000000000000
RCX: 0000000000000040
RDX: 00000207c1b00d50
RBP: 0000000000000000
RSP: 00000073fcdcf920
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff9cf41cc91
R8:  0000000000000010
R9:  00000207c1b30000
R10: 00000073fcdce159
R11: 0000000000000004
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.0.5] alphalaneous.editortab_api
x | [v1.5.0] alphalaneous.happy_textures
x | [v1.0.4] ata.completions
x | [v1.1.2] bitz.customprofiles
x | [v1.2.5] blueblock6.cleanstartpos
x | [v1.0.0] burhanyasir.again
  | [v1.0.0] burhanyasir.experiment
x | [v1.0.7] cdc.level_thumbnails
x | [v1.0.3] cgytrus.level-shaders-fix
x | [v4.2.10] cvolton.betterinfo
x | [v1.0.1] cvolton.level-id-api
x | [v1.2.1] cvolton.misc_bugfixes
x | [v1.0.0-beta.2] eclipse.eclipse-menu
x | [v1.3.3-alpha.2] elnexreal.copy_song_id
x | [v2.3.4] elohmrow.death_tracker
x | [v1.0.1] fig.authentication
x | [v1.0.9] firee.goldenbest
x | [v1.3.1] firee.object-workshop
x | [v1.2.0] firefly7386.savesongs
x | [v0.3.2] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.9.0] geode.custom-keybinds
x | [v1.7.0] geode.devtools
x | [v3.8.1] geode.loader
x | [v1.15.0] geode.node-ids
x | [v1.6.2] geode.texture-loader
x | [v1.6.3] hiimjustin000.integrated_demonlist
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.0.0] hjfod.bettersave_recovery
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.0.3] iswilljr.enter-search
x | [v1.2.1] itzkiba.better_progression
x | [v1.0.4] mat.max-window
x | [v1.2.1] mat.run-info
x | [v1.1.0] mobmastermind.encouraging-quotes
  | [v1.6.0] prevter.bettercrash
x | [v1.0.0-alpha.2] sabe.persistenceapi
x | [v1.0.1-alpha.3] sabe.platformersaves
x | [v1.0.0] sorkopiko.playlists
x | [v1.1.0] spaghettdev.songpreview
x | [v1.2.2] syzzi.click_between_frames
x | [v1.3.4] uproxide.textures

**Comment by BurhanYasir123** [comment]
and in the console it says it has a update avalible but gd wont stay open for even 5 sec

**Comment by hiimjasmine00** [comment]
https://youtu.be/vk0k57b_tD8
