### ISSUE TITLE
A option to adjust where the button is

### ISSUE THREAD

**Issue by Infernogd** [hiimjustin000/IntegratedDemonlist#2]
Hi I have the intergrated loquibot and the intergrated demonlist together but they overlap is there a way too adjust where the button can be placed? thanks
![image_2024-03-24_132938453](https://github.com/hiimjustin000/IntegratedDemonlist/assets/164727301/dcfcdf33-5115-491f-bb15-d383f7e8f7dd)

**Comment by InfernoZv** [comment]
nvm figured something out
