### ISSUE TITLE
Suggestion (Not issue sorry)

### ISSUE THREAD

**Issue by BXDashh** [hiimjustin000/IntegratedDemonlist#4]
![suggest](https://github.com/hiimjustin000/IntegratedDemonlist/assets/173524705/8baf9cad-5469-4f22-a53f-f28b3078613c)
I want to suggest that all extreme demons could have their own ranking below the demon difficulty.

**Comment by hiimjasmine00** [comment]
There is a mod that does this (IngameListMod by Adya). However, it's not cross-platform.
