### ISSUE TITLE
mod crashes when dark-mode v4 is enabled again

### ISSUE THREAD

**Issue by Infernogd** [hiimjustin000/IntegratedDemonlist#5]
Yeah mod crashes when dark mode v4 mod is enabled again!  Please fix again thanks :)

**Comment by hiimjasmine00** [comment]
Bug caused by DarkMode V4, forwarding this to @iArtie

Caused by this line of code -> https://github.com/v1.0.2/DarkMode-V4/blob/master/src/main.cpp#L540

Fixed by https://github.com/iArtie/DarkMode-V4/pull/4
